### PR TITLE
update for latest eman version

### PR DESCRIPTION
**Pull request by azazellochg**
Tests passing with eman2.99

### CODE REVIEW

**Comment by azazellochg** [comment]
I need to make some changes, please ignore for now

**Comment by azazellochg** [comment]
Now ready for review

**Review by pconesa — APPROVED** [review]

**Comment by azazellochg** [comment]
@pconesa did the install work for you?

**Comment by pconesa** [comment]
Actually not! Didn't test it. 

I'm getting this:

````
echo " > Installing mpi4py in eman2" && conda activate /home/pablo/software/scipion/software/em/eman-2.99 && conda install -c conda-forge openmpi-mpicc && pip install mpi4py
 > Installing mpi4py in eman2
/bin/sh: 1: conda: not found
````

I think somehow we need to be able to "activate EMAN2's conda", which might be tricky.

**Comment by azazellochg** [comment]
Looks like conda itself is not sourced

**Comment by azazellochg** [comment]
How about now?

**Pull request merged**
