### PR TITLE
adding locscale 2.1

### LINKED ISSUE #14: add version 2.0 support
https://gitlab.tudelft.nl/aj-lab/locscale

### PR DESCRIPTION
**Pull request by azazellochg**
closes #14

### CODE REVIEW

**Comment by azazellochg** [comment]
1 out of 3 tests still fails with:
```
00014:     File "/home/gsharov/soft/miniconda3/envs/locscale-2.1/lib/python3.8/site-packages/locscale/preprocessing/pseudomodel_classes.py", line 303, in extract_model_from_mask
00015:       points = [Atom(np.array([x[2]+np.random.uniform(-0.5,0.5),x[1]+np.random.uniform(-0.5,0.5),x[0]+np.random.uniform(-0.5,0.5)])) for x in random.sample(population,num_atoms)]
00016:     File "/home/gsharov/soft/miniconda3/envs/locscale-2.1/lib/python3.8/random.py", line 363, in sample
00017:       raise ValueError("Sample larger than population or is negative")
00018:   ValueError: Sample larger than population or is negative
```

**Comment by pconesa** [comment]
I got this error during "binary installation":

      Preparing transaction: ...working... done
      Verifying transaction: ...working... done
      Executing transaction: ...working... done
      /tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/dist.py:757: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py:623: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
      Please extend command classes from setuptools instead of distutils.
        warnings.warn(
      Traceback (most recent call last):
        File "/extra/miniconda3/envs/locscale-2.1/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/extra/miniconda3/envs/locscale-2.1/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/extra/miniconda3/envs/locscale-2.1/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 70, in <module>
          setup(name='locscale',
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-7u5j2e7i/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "setup.py", line 64, in run
          raise UserWarning("Refmac5 is not installed. Please install CCP4 before running locscale. Without Refmac locscale cannot refine the input atomic structure.")
      UserWarning: Refmac5 is not installed. Please install CCP4 before running locscale. Without Refmac locscale cannot refine the input atomic structure.
      [end of output]

**Comment by pconesa** [comment]
is it strongly coupled with refmac?

**Comment by azazellochg** [comment]
Hi Pablo, yes the installer of the locscale itself checks for refmac
presence. So, you need to have ccp4 plugin and binaries installed
Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: ***@***.***

**Comment by azazellochg** [comment]
@pconesa you can try again, now ccp4 dependency can be avoided

**Review by fonsecareyna82 — APPROVED** [review]

**Pull request merged**
